// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klxpvgxxmxjjfmtskdfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtseHB2Z3h4bXhqamZtdHNrZGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTI1MDYsImV4cCI6MjA1OTg2ODUwNn0.5r-c1-iAmhMv2-TWqGTqgNYbDgsW4gx8edv_PlPon9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);